name: release-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "release from"
        required: true
        default: "master"
      tag:
        description: "release tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.branch }}"

      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Prepare version
        run: cd shared; echo "${{ github.event.inputs.tag }}" > pkg/version/buildversion; make build_version; cd ../

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.event.inputs.branch }}
          message: "release ${{ github.event.inputs.tag }}"

      - name: Build relayer
        run: cd relayer; make all; cd ../

      - name: Release log
        run: cd relayer/build/cmd/relayer; ls | grep -v ".tar.gz" | while read line; do tar zcvf $line.tar.gz $line; openssl dgst -sha256 $line.tar.gz >> release.sha256.log; done; cd ../../../../

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.inputs.tag }}"
          commit: "${{ github.event.inputs.branch }}"
          artifacts: "relayer/build/cmd/relayer/*.tar.gz"
          bodyFile: "relayer/build/cmd/relayer/release.sha256.log"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}